[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd /app/backend && NODE_ENV=development npm ci"]

[phases.build]
cmds = ["cd /app/backend && npm run build"]

[start]
cmd = "cd /app/backend && npm start"
